// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteUmbracoSproutFormsFormData, DeleteUmbracoSproutFormsFormResponses, GetUmbracoSproutFormsAncestorsData, GetUmbracoSproutFormsAncestorsResponses, GetUmbracoSproutFormsChildrenData, GetUmbracoSproutFormsChildrenResponses, GetUmbracoSproutFormsDashboardData, GetUmbracoSproutFormsDashboardResponses, GetUmbracoSproutFormsFieldTypesData, GetUmbracoSproutFormsFieldTypesResponses, GetUmbracoSproutFormsFormData, GetUmbracoSproutFormsFormResponses, GetUmbracoSproutFormsFormsData, GetUmbracoSproutFormsFormsResponses, GetUmbracoSproutFormsOutcomeTypesData, GetUmbracoSproutFormsOutcomeTypesResponses, GetUmbracoSproutFormsRootData, GetUmbracoSproutFormsRootResponses, GetUmbracoSproutFormsSubmissionData, GetUmbracoSproutFormsSubmissionResponses, GetUmbracoSproutFormsSubmissionsData, GetUmbracoSproutFormsSubmissionsResponses, GetUmbracoSproutFormsWorkflowTypesData, GetUmbracoSproutFormsWorkflowTypesResponses, PostUmbracoSproutFormsFolderData, PostUmbracoSproutFormsFolderResponses, PostUmbracoSproutFormsFormData, PostUmbracoSproutFormsFormResponses, PostUmbracoSproutFormsGenerateAliasData, PostUmbracoSproutFormsGenerateAliasResponses, PostUmbracoSproutFormsSubmissionWorkflowApproveData, PostUmbracoSproutFormsSubmissionWorkflowApproveResponses, PostUmbracoSproutFormsSubmissionWorkflowDeclineData, PostUmbracoSproutFormsSubmissionWorkflowDeclineResponses, PostUmbracoSproutFormsSubmissionWorkflowRetryData, PostUmbracoSproutFormsSubmissionWorkflowRetryResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BackofficeSproutForms {
    public static getUmbracoSproutFormsAncestors<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsAncestorsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsAncestorsResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/ancestors',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsChildren<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsChildrenData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsChildrenResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/children',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsDashboard<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsDashboardData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsDashboardResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/dashboard',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsFieldTypes<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsFieldTypesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsFieldTypesResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/fieldTypes',
            ...options
        });
    }
    
    public static postUmbracoSproutFormsFolder<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoSproutFormsFolderData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoSproutFormsFolderResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/folder',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteUmbracoSproutFormsForm<ThrowOnError extends boolean = true>(options?: Options<DeleteUmbracoSproutFormsFormData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteUmbracoSproutFormsFormResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/form',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getUmbracoSproutFormsForm<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsFormData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsFormResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/form',
            ...options
        });
    }
    
    public static postUmbracoSproutFormsForm<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoSproutFormsFormData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoSproutFormsFormResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/form',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getUmbracoSproutFormsForms<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsFormsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsFormsResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/forms',
            ...options
        });
    }
    
    public static postUmbracoSproutFormsGenerateAlias<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoSproutFormsGenerateAliasData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoSproutFormsGenerateAliasResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/generateAlias',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsOutcomeTypes<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsOutcomeTypesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsOutcomeTypesResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/outcomeTypes',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsRoot<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsRootData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsRootResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/root',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsSubmission<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsSubmissionData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsSubmissionResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/submission',
            ...options
        });
    }
    
    public static postUmbracoSproutFormsSubmissionWorkflowApprove<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoSproutFormsSubmissionWorkflowApproveData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoSproutFormsSubmissionWorkflowApproveResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/submission/workflow/approve',
            ...options
        });
    }
    
    public static postUmbracoSproutFormsSubmissionWorkflowDecline<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoSproutFormsSubmissionWorkflowDeclineData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoSproutFormsSubmissionWorkflowDeclineResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/submission/workflow/decline',
            ...options
        });
    }
    
    public static postUmbracoSproutFormsSubmissionWorkflowRetry<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoSproutFormsSubmissionWorkflowRetryData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoSproutFormsSubmissionWorkflowRetryResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/submission/workflow/retry',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsSubmissions<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsSubmissionsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsSubmissionsResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/submissions',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsWorkflowTypes<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsWorkflowTypesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsWorkflowTypesResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/workflowTypes',
            ...options
        });
    }
}
