// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteUmbracoSproutFormsFormData, DeleteUmbracoSproutFormsFormResponses, GetUmbracoSproutFormsFieldTypesData, GetUmbracoSproutFormsFieldTypesResponses, GetUmbracoSproutFormsFormData, GetUmbracoSproutFormsFormResponses, GetUmbracoSproutFormsFormsData, GetUmbracoSproutFormsFormsResponses, GetUmbracoSproutFormsOutcomeTypesData, GetUmbracoSproutFormsOutcomeTypesResponses, GetUmbracoSproutFormsSubmissionData, GetUmbracoSproutFormsSubmissionResponses, GetUmbracoSproutFormsSubmissionsData, GetUmbracoSproutFormsSubmissionsResponses, GetUmbracoSproutFormsWorkflowTypesData, GetUmbracoSproutFormsWorkflowTypesResponses, PostUmbracoSproutFormsFormData, PostUmbracoSproutFormsFormResponses, PostUmbracoSproutFormsGenerateAliasData, PostUmbracoSproutFormsGenerateAliasResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BackofficeSproutForms {
    public static getUmbracoSproutFormsFieldTypes<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsFieldTypesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsFieldTypesResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/fieldTypes',
            ...options
        });
    }
    
    public static deleteUmbracoSproutFormsForm<ThrowOnError extends boolean = true>(options?: Options<DeleteUmbracoSproutFormsFormData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteUmbracoSproutFormsFormResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/form',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getUmbracoSproutFormsForm<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsFormData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsFormResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/form',
            ...options
        });
    }
    
    public static postUmbracoSproutFormsForm<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoSproutFormsFormData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoSproutFormsFormResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/form',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getUmbracoSproutFormsForms<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsFormsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsFormsResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/forms',
            ...options
        });
    }
    
    public static postUmbracoSproutFormsGenerateAlias<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoSproutFormsGenerateAliasData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoSproutFormsGenerateAliasResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/generateAlias',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsOutcomeTypes<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsOutcomeTypesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsOutcomeTypesResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/outcomeTypes',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsSubmission<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsSubmissionData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsSubmissionResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/submission',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsSubmissions<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsSubmissionsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsSubmissionsResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/submissions',
            ...options
        });
    }
    
    public static getUmbracoSproutFormsWorkflowTypes<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSproutFormsWorkflowTypesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSproutFormsWorkflowTypesResponses, unknown, ThrowOnError>({
            url: '/umbraco/sproutForms/workflowTypes',
            ...options
        });
    }
}
