// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:62959' | (string & {});
};

export enum ConditionComparison {
    EQUALS = 'Equals',
    NOT_EQUALS = 'NotEquals',
    CONTAINS = 'Contains',
    GREATER_THAN = 'GreaterThan',
    LESS_THAN = 'LessThan',
    IS_EMPTY = 'IsEmpty',
    IS_NOT_EMPTY = 'IsNotEmpty',
    MATCHES_REGEX = 'MatchesRegex',
    DOES_NOT_MATCH_REGEX = 'DoesNotMatchRegex'
}

export type ConditionDefinition = {
    operator: string;
    rules: Array<ConditionRule>;
};

export type ConditionRule = {
    fieldAlias: string;
    comparison: ConditionComparison;
    value?: unknown;
};

export type CreateFolderRequest = {
    name: string;
    parentId?: string | null;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type FieldConditions = {
    visibility?: ConditionDefinition | null;
    required?: ConditionDefinition | null;
};

export type FormBackofficeModel = {
    id?: string | null;
    folderId?: string | null;
    name: string;
    alias: string;
    version: number;
    source: number;
    definition: FormDefinitionBackofficeModel;
};

export type FormColumnBackofficeModel = {
    width: number;
    fieldAlias: string;
};

export type FormDefinitionBackofficeModel = {
    rows: Array<FormRowBackofficeModel>;
    fields: Array<FormFieldBackofficeModel>;
    outcome: FormOutcomeBackofficeModel;
    workflows: Array<FormWorkflowBackofficeModel>;
};

export type FormFieldBackofficeModel = {
    alias: string;
    label: string;
    fieldTypeAlias: string;
    required: boolean;
    configuration: {
        [key: string]: unknown;
    };
    conditions?: FieldConditions | null;
};

export type FormFieldTypeBackofficeModel = {
    alias: string;
    displayName: string;
    icon: string;
    properties: Array<FormPropertyBackofficeModel>;
};

export type FormFlowTypeBackofficeModel = {
    alias: string;
    displayName: string;
    configuration: Array<FormPropertyBackofficeModel>;
};

export type FormListBackofficeModel = {
    id: string;
    name: string;
    source: number;
    totalSubmissions: number;
};

export type FormOutcomeBackofficeModel = {
    typeAlias: string;
    displayName: string;
    configuration: {
        [key: string]: unknown;
    };
};

export type FormOutcomeTypeBackofficeModel = {
    alias: string;
    displayName: string;
    properties: Array<FormPropertyBackofficeModel>;
};

export type FormPropertyBackofficeModel = {
    alias: string;
    displayName: string;
    propertyEditor: string;
    value?: unknown;
};

export type FormRowBackofficeModel = {
    columns: Array<FormColumnBackofficeModel>;
};

export type FormSubmissionBackofficeModel = {
    id: string;
    values: Array<FormSubmissionValueBackofficeModel>;
};

export type FormSubmissionListItemBackofficeModel = {
    id: string;
    name: string;
};

export type FormSubmissionValueBackofficeModel = {
    fieldTypeAlias: string;
    name: string;
    value: string;
};

export type FormTreeItemModel = {
    hasChildren: boolean;
    id: string;
    name: string;
    itemType: TreeItemType;
    source?: number | null;
    totalSubmissions?: number | null;
};

export type FormWorkflowBackofficeModel = {
    alias: string;
    typeAlias: string;
    displayName: string;
    order: number;
    configuration: {
        [key: string]: unknown;
    };
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedFormListBackofficeModel = {
    total: number;
    items: Array<FormListBackofficeModel>;
};

export type PagedFormSubmissionListItemBackofficeModel = {
    total: number;
    items: Array<FormSubmissionListItemBackofficeModel>;
};

export type PagedFormTreeItemModel = {
    total: number;
    items: Array<FormTreeItemModel>;
};

export enum TreeItemType {
    FOLDER = 'Folder',
    FORM = 'Form'
}

export type GetUmbracoSproutFormsAncestorsData = {
    body?: never;
    path?: never;
    query?: {
        descendantId?: string;
    };
    url: '/umbraco/sproutForms/ancestors';
};

export type GetUmbracoSproutFormsAncestorsResponses = {
    /**
     * OK
     */
    200: Array<FormTreeItemModel>;
};

export type GetUmbracoSproutFormsAncestorsResponse = GetUmbracoSproutFormsAncestorsResponses[keyof GetUmbracoSproutFormsAncestorsResponses];

export type GetUmbracoSproutFormsChildrenData = {
    body?: never;
    path?: never;
    query?: {
        parentUnique?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/sproutForms/children';
};

export type GetUmbracoSproutFormsChildrenResponses = {
    /**
     * OK
     */
    200: PagedFormTreeItemModel;
};

export type GetUmbracoSproutFormsChildrenResponse = GetUmbracoSproutFormsChildrenResponses[keyof GetUmbracoSproutFormsChildrenResponses];

export type GetUmbracoSproutFormsFieldTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/sproutForms/fieldTypes';
};

export type GetUmbracoSproutFormsFieldTypesResponses = {
    /**
     * OK
     */
    200: Array<FormFieldTypeBackofficeModel>;
};

export type GetUmbracoSproutFormsFieldTypesResponse = GetUmbracoSproutFormsFieldTypesResponses[keyof GetUmbracoSproutFormsFieldTypesResponses];

export type PostUmbracoSproutFormsFolderData = {
    body?: CreateFolderRequest;
    path?: never;
    query?: never;
    url: '/umbraco/sproutForms/folder';
};

export type PostUmbracoSproutFormsFolderResponses = {
    /**
     * OK
     */
    200: FormTreeItemModel;
};

export type PostUmbracoSproutFormsFolderResponse = PostUmbracoSproutFormsFolderResponses[keyof PostUmbracoSproutFormsFolderResponses];

export type DeleteUmbracoSproutFormsFormData = {
    body?: Array<string>;
    path?: never;
    query?: never;
    url: '/umbraco/sproutForms/form';
};

export type DeleteUmbracoSproutFormsFormResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSproutFormsFormData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/sproutForms/form';
};

export type GetUmbracoSproutFormsFormResponses = {
    /**
     * OK
     */
    200: FormBackofficeModel;
};

export type GetUmbracoSproutFormsFormResponse = GetUmbracoSproutFormsFormResponses[keyof GetUmbracoSproutFormsFormResponses];

export type PostUmbracoSproutFormsFormData = {
    body?: FormBackofficeModel;
    path?: never;
    query?: never;
    url: '/umbraco/sproutForms/form';
};

export type PostUmbracoSproutFormsFormResponses = {
    /**
     * OK
     */
    200: FormBackofficeModel;
};

export type PostUmbracoSproutFormsFormResponse = PostUmbracoSproutFormsFormResponses[keyof PostUmbracoSproutFormsFormResponses];

export type GetUmbracoSproutFormsFormsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/sproutForms/forms';
};

export type GetUmbracoSproutFormsFormsResponses = {
    /**
     * OK
     */
    200: PagedFormListBackofficeModel;
};

export type GetUmbracoSproutFormsFormsResponse = GetUmbracoSproutFormsFormsResponses[keyof GetUmbracoSproutFormsFormsResponses];

export type PostUmbracoSproutFormsGenerateAliasData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        name?: string;
    };
    url: '/umbraco/sproutForms/generateAlias';
};

export type PostUmbracoSproutFormsGenerateAliasResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostUmbracoSproutFormsGenerateAliasResponse = PostUmbracoSproutFormsGenerateAliasResponses[keyof PostUmbracoSproutFormsGenerateAliasResponses];

export type GetUmbracoSproutFormsOutcomeTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/sproutForms/outcomeTypes';
};

export type GetUmbracoSproutFormsOutcomeTypesResponses = {
    /**
     * OK
     */
    200: Array<FormOutcomeTypeBackofficeModel>;
};

export type GetUmbracoSproutFormsOutcomeTypesResponse = GetUmbracoSproutFormsOutcomeTypesResponses[keyof GetUmbracoSproutFormsOutcomeTypesResponses];

export type GetUmbracoSproutFormsRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/sproutForms/root';
};

export type GetUmbracoSproutFormsRootResponses = {
    /**
     * OK
     */
    200: PagedFormTreeItemModel;
};

export type GetUmbracoSproutFormsRootResponse = GetUmbracoSproutFormsRootResponses[keyof GetUmbracoSproutFormsRootResponses];

export type GetUmbracoSproutFormsSubmissionData = {
    body?: never;
    path?: never;
    query?: {
        submissionId?: string;
    };
    url: '/umbraco/sproutForms/submission';
};

export type GetUmbracoSproutFormsSubmissionResponses = {
    /**
     * OK
     */
    200: FormSubmissionBackofficeModel;
};

export type GetUmbracoSproutFormsSubmissionResponse = GetUmbracoSproutFormsSubmissionResponses[keyof GetUmbracoSproutFormsSubmissionResponses];

export type GetUmbracoSproutFormsSubmissionsData = {
    body?: never;
    path?: never;
    query?: {
        formId?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/sproutForms/submissions';
};

export type GetUmbracoSproutFormsSubmissionsResponses = {
    /**
     * OK
     */
    200: PagedFormSubmissionListItemBackofficeModel;
};

export type GetUmbracoSproutFormsSubmissionsResponse = GetUmbracoSproutFormsSubmissionsResponses[keyof GetUmbracoSproutFormsSubmissionsResponses];

export type GetUmbracoSproutFormsWorkflowTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/sproutForms/workflowTypes';
};

export type GetUmbracoSproutFormsWorkflowTypesResponses = {
    /**
     * OK
     */
    200: Array<FormFlowTypeBackofficeModel>;
};

export type GetUmbracoSproutFormsWorkflowTypesResponse = GetUmbracoSproutFormsWorkflowTypesResponses[keyof GetUmbracoSproutFormsWorkflowTypesResponses];
