// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5970' | (string & {});
};

export const ConditionComparison = {
    EQUALS: 'Equals',
    NOT_EQUALS: 'NotEquals',
    CONTAINS: 'Contains',
    GREATER_THAN: 'GreaterThan',
    LESS_THAN: 'LessThan',
    IS_EMPTY: 'IsEmpty',
    IS_NOT_EMPTY: 'IsNotEmpty',
    MATCHES_REGEX: 'MatchesRegex',
    DOES_NOT_MATCH_REGEX: 'DoesNotMatchRegex'
} as const;

export type ConditionComparison = typeof ConditionComparison[keyof typeof ConditionComparison];

export type ConditionDefinition = {
    operator: string;
    rules: Array<ConditionRule>;
};

export type ConditionRule = {
    fieldAlias: string;
    comparison: ConditionComparison;
    value?: unknown;
};

export const EventMessageTypeModel = {
    DEFAULT: 'Default',
    INFO: 'Info',
    ERROR: 'Error',
    SUCCESS: 'Success',
    WARNING: 'Warning'
} as const;

export type EventMessageTypeModel = typeof EventMessageTypeModel[keyof typeof EventMessageTypeModel];

export type FieldConditions = {
    visibility?: ConditionDefinition | null;
    required?: ConditionDefinition | null;
};

export type FormClientColumn = {
    width: number;
    field: FormClientField;
};

export type FormClientField = {
    alias: string;
    label: string;
    type: string;
    required: boolean;
    rendersOwnLabel: boolean;
    configuration?: unknown;
    conditions?: FieldConditions | null;
    validationRules: Array<ValidationRule>;
    extension?: unknown;
    rows?: Array<FormClientRow> | null;
};

export type FormClientModel = {
    id: string;
    alias: string;
    versionId: string;
    formType: string;
    formTypeSettings?: unknown;
    submitLabel: string;
    showProgress: boolean;
    pages: Array<FormClientPage>;
    submissionGuard?: FormClientSubmissionGuard | null;
    texts: FormClientTexts;
};

export type FormClientPage = {
    index: number;
    title?: string | null;
    progressLabel: string;
    nextLabel: string;
    previousLabel: string;
    visibility?: ConditionDefinition | null;
    rows: Array<FormClientRow>;
};

export type FormClientRow = {
    columns: Array<FormClientColumn>;
};

export type FormClientSubmissionGuard = {
    alias: string;
    settings?: unknown;
};

export type FormClientTexts = {
    required: string;
    invalid: string;
    submitFailed: string;
    submitSucceeded: string;
};

export type HeadlessOutcome = {
    type: string;
    data: {
        [key: string]: unknown;
    };
};

export type HeadlessSubmitResponse = {
    outcome?: HeadlessOutcome | null;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | {
        [key: string]: Array<string>;
    } | undefined;
};

export type ValidationRule = {
    type: string;
    value?: unknown;
    message?: string | null;
};

export type GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasData = {
    body?: never;
    path: {
        idOrAlias: string;
    };
    query?: never;
    url: '/umbraco/sproutforms/delivery/api/v1/definitions/{idOrAlias}';
};

export type GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasResponses = {
    /**
     * OK
     */
    200: FormClientModel;
};

export type GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasResponse = GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasResponses[keyof GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasResponses];

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/sproutforms/delivery/api/v1/entries/{id}';
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Unsupported Media Type
     */
    415: unknown;
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdError = PostUmbracoSproutformsDeliveryApiV1EntriesByIdErrors[keyof PostUmbracoSproutformsDeliveryApiV1EntriesByIdErrors];

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdResponses = {
    /**
     * OK
     */
    200: HeadlessSubmitResponse;
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdResponse = PostUmbracoSproutformsDeliveryApiV1EntriesByIdResponses[keyof PostUmbracoSproutformsDeliveryApiV1EntriesByIdResponses];

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateData = {
    body?: {
        [key: string]: unknown;
    };
    path: {
        id: string;
        pageIndex: number;
    };
    query?: never;
    url: '/umbraco/sproutforms/delivery/api/v1/entries/{id}/pages/{pageIndex}/validate';
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateError = PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateErrors[keyof PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateErrors];

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateResponse = PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateResponses[keyof PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateResponses];
