// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5970' | (string & {});
};

export type CalculationOperand = {
    source: ConditionValueSource;
    value?: unknown;
};

export const CalculationOperation = {
    SET: 'Set',
    ADD: 'Add',
    SUBTRACT: 'Subtract',
    MULTIPLY: 'Multiply',
    DIVIDE: 'Divide',
    APPEND: 'Append'
} as const;

export type CalculationOperation = typeof CalculationOperation[keyof typeof CalculationOperation];

export type CalculationRule = {
    condition?: ConditionDefinition | null;
    variableAlias: string;
    operation: CalculationOperation;
    operand: CalculationOperand;
    ownerFieldAlias?: string | null;
};

export const ConditionComparison = {
    EQUALS: 'Equals',
    NOT_EQUALS: 'NotEquals',
    CONTAINS: 'Contains',
    GREATER_THAN: 'GreaterThan',
    LESS_THAN: 'LessThan',
    IS_EMPTY: 'IsEmpty',
    IS_NOT_EMPTY: 'IsNotEmpty',
    MATCHES_REGEX: 'MatchesRegex',
    DOES_NOT_MATCH_REGEX: 'DoesNotMatchRegex'
} as const;

export type ConditionComparison = typeof ConditionComparison[keyof typeof ConditionComparison];

export type ConditionDefinition = {
    operator: string;
    rules: Array<ConditionRule>;
};

export type ConditionRule = {
    fieldAlias: string;
    variableAlias?: string | null;
    comparison: ConditionComparison;
    value?: unknown;
    valueSource: ConditionValueSource;
};

export const ConditionValueSource = {
    VALUE: 'Value',
    FIELD: 'Field',
    VARIABLE: 'Variable'
} as const;

export type ConditionValueSource = typeof ConditionValueSource[keyof typeof ConditionValueSource];

export const EventMessageTypeModel = {
    DEFAULT: 'Default',
    INFO: 'Info',
    ERROR: 'Error',
    SUCCESS: 'Success',
    WARNING: 'Warning'
} as const;

export type EventMessageTypeModel = typeof EventMessageTypeModel[keyof typeof EventMessageTypeModel];

export type FieldRule = {
    condition: ConditionDefinition;
    action: FieldRuleAction;
};

export const FieldRuleAction = {
    SHOW: 'Show',
    HIDE: 'Hide',
    REQUIRE: 'Require'
} as const;

export type FieldRuleAction = typeof FieldRuleAction[keyof typeof FieldRuleAction];

export type FormClientColumn = {
    width: number;
    field: FormClientField;
};

export type FormClientField = {
    alias: string;
    label: string;
    type: string;
    required: boolean;
    rendersOwnLabel: boolean;
    configuration?: unknown;
    rules: Array<FieldRule>;
    validationRules: Array<ValidationRule>;
    extension?: unknown;
    rows?: Array<FormClientRow> | null;
};

export type FormClientModel = {
    id: string;
    alias: string;
    versionId: string;
    formType: string;
    formTypeSettings?: unknown;
    submitLabel: string;
    showProgress: boolean;
    pages: Array<FormClientPage>;
    variables: Array<FormClientVariable>;
    calculations: Array<CalculationRule>;
    submissionGuard?: FormClientSubmissionGuard | null;
    texts: FormClientTexts;
};

export type FormClientPage = {
    index: number;
    title?: string | null;
    progressLabel: string;
    nextLabel: string;
    previousLabel: string;
    visibility?: ConditionDefinition | null;
    rows: Array<FormClientRow>;
};

export type FormClientRow = {
    columns: Array<FormClientColumn>;
};

export type FormClientSubmissionGuard = {
    alias: string;
    settings?: unknown;
};

export type FormClientTexts = {
    required: string;
    invalid: string;
    submitFailed: string;
    submitSucceeded: string;
};

export type FormClientVariable = {
    alias: string;
    type: FormVariableType;
    initialValue?: unknown;
    decimals: number;
};

export const FormVariableType = {
    NUMBER: 'Number',
    TEXT: 'Text'
} as const;

export type FormVariableType = typeof FormVariableType[keyof typeof FormVariableType];

export type HeadlessOutcome = {
    type: string;
    data: {
        [key: string]: unknown;
    };
};

export type HeadlessSubmitResponse = {
    outcome?: HeadlessOutcome | null;
    variables: {
        [key: string]: unknown;
    };
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | {
        [key: string]: Array<string>;
    } | undefined;
};

export type ValidationRule = {
    type: string;
    value?: unknown;
    message?: string | null;
};

export type GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasData = {
    body?: never;
    path: {
        idOrAlias: string;
    };
    query?: never;
    url: '/umbraco/sproutforms/delivery/api/v1/definitions/{idOrAlias}';
};

export type GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasResponses = {
    /**
     * OK
     */
    200: FormClientModel;
};

export type GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasResponse = GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasResponses[keyof GetUmbracoSproutformsDeliveryApiV1DefinitionsByIdOrAliasResponses];

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdData = {
    /**
     * The values keyed by field alias, a repeater's as a list of entry objects. Texts, numbers and booleans are all taken as text. "sf_PageUrl" holds the page the form was on, and the submission guard's values sit next to the fields, such as "g-recaptcha-response" or the honeypot's field.
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/sproutforms/delivery/api/v1/entries/{id}';
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Unsupported Media Type
     */
    415: unknown;
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdError = PostUmbracoSproutformsDeliveryApiV1EntriesByIdErrors[keyof PostUmbracoSproutformsDeliveryApiV1EntriesByIdErrors];

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdResponses = {
    /**
     * OK
     */
    200: HeadlessSubmitResponse;
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdResponse = PostUmbracoSproutformsDeliveryApiV1EntriesByIdResponses[keyof PostUmbracoSproutformsDeliveryApiV1EntriesByIdResponses];

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateData = {
    body?: {
        [key: string]: unknown;
    };
    path: {
        id: string;
        pageIndex: number;
    };
    query?: never;
    url: '/umbraco/sproutforms/delivery/api/v1/entries/{id}/pages/{pageIndex}/validate';
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateError = PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateErrors[keyof PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateErrors];

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateResponse = PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateResponses[keyof PostUmbracoSproutformsDeliveryApiV1EntriesByIdPagesByPageIndexValidateResponses];
